---
env:
  TERM: xterm-256color

import:
  - ~/.config/alacritty/themes/dracula.yml

window:
  dimensions:
    columns: 110
    lines: 30
  opacity: 0.8
  title: Alacritty
  dynamic_title: true
  class:
    instance: Alacritty
    general: Alacritty

scrolling:
  history: 100000
  multiplier: 6

font:
  normal:
    family: JetBrainsMono Nerd Font Mono
    style: Regular

  bold:
    family: JetBrainsMono Nerd Font Mono
    style: Bold

  italic:
    family: JetBrainsMono Nerd Font Mono
    style: Italic

  bold_italic:
    family: JetBrainsMono Nerd Font Mono
    style: Bold Italic

  size: 14

builtin_box_drawing: true
draw_bold_text_with_bright_colors: true

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

cursor:
  style:
    shape: Beam
    blinking: Always
  unfocused_hollow: false

shell:
  program: /bin/fish

key_bindings:
  - { key: V,         mods: Control|Shift, action: Paste                       }
  - { key: C,         mods: Control|Shift, action: Copy                        }
  - { key: Insert,    mods: Shift,         action: PasteSelection              }
  - { key: Key0,      mods: Control,       action: ResetFontSize               }
  - { key: Equals,    mods: Control,       action: IncreaseFontSize            }
  - { key: Plus,      mods: Control,       action: IncreaseFontSize            }
  - { key: Minus,     mods: Control,       action: DecreaseFontSize            }
  - { key: F11,       mods: None,          action: ToggleFullscreen            }
  - { key: Paste,     mods: None,          action: Paste                       }
  - { key: Copy,      mods: None,          action: Copy                        }
  - { key: L,         mods: Control,       action: ClearLogNotice              }
  - { key: L,         mods: Control,       chars: "\x0c"                       }
  - { key: PageUp,    mods: None,          action: ScrollPageUp,   mode: ~Alt  }
  - { key: PageDown,  mods: None,          action: ScrollPageDown, mode: ~Alt  }
  - { key: Home,      mods: Shift,         action: ScrollToTop,    mode: ~Alt  }
  - { key: End,       mods: Shift,         action: ScrollToBottom, mode: ~Alt  }

