#! /bin/sh

xsetroot -cursor_name left_ptr &
pgrep -x sxhkd > /dev/null || sxhkd &
# mname BSPWM &





# monitors=$(xrandr --query | grep " connected" | cut -d" " -f1)

# if [ ${#monitor[@]} -gt 1 ]; then
#   for monitor in $monitors; do
#    bspc monitor -d 1 2 6 7 8 9 0
#  done
# else
#   bspc monitor -d 1 2 3 4 5 6 7 8 9 0
# fi

bspc monitor eDP -d I II III IV V
bspc monitor DisplayPort-0 -d VI VII VIII IX X

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config split_ratio          0.52
bspc config border_width         2
bspc config window_gap           10
bspc config focused_border_color '#bd93f9'
#bspc config focus_follows_pointer true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a netease-cloud-music desktop='^6' state=floating
