#! /bin/sh

xsetroot -cursor_name left_ptr &
pgrep -x sxhkd > /dev/null || sxhkd &
# mname BSPWM &





monitors="$(bspc query -M --names)"
if [ ${#monitors[@]} -eq 1 ] ; then
	bspc monitor -d I II III IV V VI VII VIII IX X
else
	bspc monitor ${monitors[0]} -d I II III IV V
  bspc monitor ${monitors[1]} -d VI VII VIII IX X
fi


bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config split_ratio          0.52
bspc config border_width         2
bspc config window_gap           10
# bspc config normal_border_color ''
bspc config focused_border_color '#bd93f9'
#bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus false

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a netease-cloud-music desktop='^5' state=floating
bspc rule -a Sxiv state=floating follow=on
bspc rule -a Zathura state=floating follow=on

