#! /bin/sh

xsetroot -cursor_name left_ptr &
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.dotfiles/scripts/autostart.sh &
#$HOME/.dotfiles/scripts/xrandr.sh &
# mname BSPWM &



monitors=($(bspc query -M --names))
if [ ${#monitors[@]} -eq 1 ] ; then
	bspc monitor -d 一 二 三 四 五 六 七 八 九 十
else
	bspc monitor "${monitors[0]}" -d 一 二 三 四 五
  bspc monitor "${monitors[1]}" -d 六 七 八 九 十
fi


bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config split_ratio          0.52
bspc config border_width         2
bspc config window_gap           10
# bspc config normal_border_color ''
bspc config focused_border_color '#bd93f9'
#bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus false

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a netease-cloud-music state=floating
bspc rule -a Sxiv state=floating follow=on
bspc rule -a Zathura state=floating follow=on
bspc rule -a Display state=floating follow=on
bspc rule -a feh state=floating follow=on
bspc rule -a LCEDA state=floating follow=on
bspc rule -a fcitx state=floating
bspc rule -a fcitx5-config-qt state=floating
bspc rule -a St state=floating follow=on
bspc rule -a Pcmanfm state=floating follow=on
bspc rule -a flameshot state=floating follow=on
bspc rule -a Alacritty state=floating follow=on
